export const getAdminList = state => state.adminList
export const getrequestList = state => state.requestList
export const getAppointmentList = state => state.appointmentList
export const getDatetList = state => state.dateList
export const getCurrentAdmin = state => state.admin
export const getLoginStatus = state => state.isLoggedIn
export const getAdminToken = state => state.adminToken
export const getDBStates = state => state.DBStats
export const getDateTiming = state => state.dateTiming
export const getDateInfo = state => state.dateInfo
export const getEventList = state => state.eventList
export const getVariables = state => state.variables
export const getVideoVar = state => state.showVideo
